# Generated by Django 5.1.1 on 2024-11-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('instagram', models.URLField(blank=True, null=True)),
                ('installment_options', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SportClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('Баскетбол', 'Баскетбол'), ('Футбол', 'Футбол'), ('Теннис', 'Теннис'), ('Плавание', 'Плавание'), ('Волейбол', 'Волейбол'), ('Тхэквондо', 'Тхэквондо'), ('Бокс', 'Бокс'), ('Велоспорт', 'Велоспорт'), ('Йога', 'Йога')], max_length=50)),
                ('class_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='class_images/')),
                ('hall_type', models.CharField(blank=True, choices=[('Основной зал', 'Основной зал'), ('Вторичный зал', 'Вторичный зал'), ('Уличная площадка', 'Уличная площадка')], max_length=50, null=True)),
                ('circle', models.CharField(blank=True, choices=[('Начинающий', 'Начинающий'), ('Средний', 'Средний'), ('Продвинутый', 'Продвинутый')], max_length=50, null=True)),
            ],
        ),
    ]
