# Generated by Django 5.1.1 on 2024-11-12 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=12, null=True, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='administrator.hall', verbose_name='Зал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активное расписание (True)'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время открытия'),
        ),
    ]
