# Generated by Django 5.1.1 on 2024-11-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('cardholder_name', models.CharField(max_length=100, verbose_name='Имя владельца карты')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('expiry_date', models.CharField(max_length=5, verbose_name='Дата истечения срока действия (MM/YY)')),
                ('cvc_code', models.CharField(max_length=3, verbose_name='CVC/CVV код')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
            },
        ),
        migrations.CreateModel(
            name='Payment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('баскетбол', 'Баскетбол'), ('футбол', 'Футбол'), ('волейбол', 'Волейбол'), ('теннис', 'Тенис'), ('бокс', 'Бокс'), ('велоспорт', 'Велоспорт'), ('таэквондо', 'Таэквондо'), ('плавание', 'Плавание'), ('йога', 'Йога')], max_length=100, verbose_name='Виды спорта')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за месяц')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basketball', 'Баскетбол'), ('football', 'Футбол'), ('tennis', 'Теннис'), ('swimming', 'Плавание'), ('volleyball', 'Волейбол'), ('taekwondo', 'Тхэквондо'), ('boxing', 'Бокс'), ('cycling', 'Велоспорт'), ('yoga', 'Йога')], max_length=50, verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
    ]
